" Example Vim graphical configuration.
" Copy to ~/.gvimrc or ~/_gvimrc.

set guifont=Ubuntu\ Mono\ Bold\ 12
set antialias                     " MacVim: smooth fonts.
set encoding=utf-8                " Use UTF-8 everywhere.
set background=light              " Background.
set lines=25 columns=100          " Window dimensions.

set guioptions-=r                 " Don't show right scrollbar

colorscheme railscasts 
