set nocompatible                  " Must come first because it changes other options.

set guifont=Ubuntu\ Mono\ Bold\ 12
filetype off

" Vundle scripts
set rtp+=~/.dotfiles/vim/bundle/vundle/
call vundle#rc()

" original repos on github
  Bundle 'chriskempson/base16-vim'
  Bundle 'gmarik/vundle'
  Bundle 'kien/ctrlp.vim'
" Bundle 'Lokaltog/vim-easymotion'
" Bundle 'rstacruz/sparkup', {'rtp': 'vim/'}
" Bundle 'tpope/vim-commentary'
" Bundle 'tpope/vim-cucumber.git'
" Bundle 'tpope/vim-endwise.git'
" Bundle 'tpope/vim-fugitive'
" Bundle 'tpope/vim-ragtag.git'
" Bundle 'tpope/vim-rails.git'
" Bundle 'tpope/vim-surround.git'
" Bundle 'tpope/vim-git.git'
" Bundle 'tpope/vim-unimpaired.git'
" Bundle 'msanders/snipmate.vim.git'
" Bundle 'scrooloose/nerdtree.git'
" Bundle 'cakebaker/scss-syntax.vim.git'
" Bundle 'ervandew/supertab.git'
" Bundle 'kchmck/vim-coffee-script.git'
" Bundle 'itspriddle/vim-jquery.git'
" Bundle 'airblade/vim-rooter.git'
  Bundle 'Lokaltog/vim-powerline.git'


"noremap <F5> :CommandTBuffer<CR>
"nnoremap <F6> :NERDTreeToggle<CR>
nnoremap <tab> :tabnext<CR>
"nnoremap <s-tab>:tabprevious<cr>

if $COLORTERM == 'gnome-terminal' 
  " set term=gnome-256color 
  colorscheme railscasts 
else 
  colorscheme default 
endif 

"silent! call pathogen#runtime_append_all_bundles()

syntax enable                     " Turn on syntax highlighting.
filetype plugin indent on         " Turn on file type detection.

runtime macros/matchit.vim        " Load the matchit plugin.

set showcmd                       " Display incomplete commands.
set showmode                      " Display the mode you're in.

set backspace=indent,eol,start    " Intuitive backspacing.

set hidden                        " Handle multiple buffers better.

set wildmenu                      " Enhanced command line completion.
set wildmode=list:longest         " Complete files like a shell.

set ignorecase                    " Case-insensitive searching.
set smartcase                     " But case-sensitive if expression contains a capital letter.

set number                        " Show line numbers.
set ruler                         " Show cursor position.

set incsearch                     " Highlight matches as you type.
set hlsearch                      " Highlight matches.

set wrap                          " Turn on line wrapping.
set scrolloff=3                   " Show 3 lines of context around the cursor.

set title                         " Set the terminal's title

set visualbell                    " No beeping.

set nobackup                      " Don't make a backup before overwriting a file.
set nowritebackup                 " And again.
set directory=$HOME/.vim/tmp//,.  " Keep swap files in one location

" UNCOMMENT TO USE
set tabstop=2                    " Global tab width.
set shiftwidth=2                 " And again, related.
set expandtab                    " Use spaces instead of tabs

set laststatus=2                  " Show the status line all the time
" Useful status information at bottom of screen
"set statusline=[%n]\ %<%.99f\ %h%w%m%r%y\ %{fugitive#statusline()}%{exists('*CapsLockStatusline')?CapsLockStatusline():''}%=%-16(\ %l,%c-%v\ %)%P
 
" Or use vividchalk
" colorscheme base16-tomorrow
" colorscheme vividchalk

" Tab mappings.
"map <leader>tt :tabnew<cr>
"map <leader>te :tabedit
"map <leader>tc :tabclose<cr>
"map <leader>to :tabonly<cr>
"map <leader>tn :tabnext<cr>
"map <leader>tp :tabprevious<cr>
"map <leader>tf :tabfirst<cr>
"map <leader>tl :tablast<cr>
"map <leader>tm :tabmove


" Automatic fold settings for specific files. Uncomment to use.
" autocmd FileType ruby setlocal foldmethod=syntax
" autocmd FileType css  setlocal foldmethod=indent shiftwidth=2 tabstop=2

" For the MakeGreen plugin and Ruby RSpec. Uncomment to use.
"autocmd BufNewFile,BufRead *_spec.rb compiler rspec
